// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUcFlTab9jaGA_KOYm7tGABIF7K6nqTs',
    appId: '1:1005309051138:web:c626363e181e7319aa021b',
    messagingSenderId: '1005309051138',
    projectId: 'thriftly-fa587',
    authDomain: 'thriftly-fa587.firebaseapp.com',
    storageBucket: 'thriftly-fa587.appspot.com',
    measurementId: 'G-XMN3V7MBBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbznKxGRvrERB0agHdh5bxiwHu17wXjrU',
    appId: '1:1005309051138:android:44b4ab8fc0509937aa021b',
    messagingSenderId: '1005309051138',
    projectId: 'thriftly-fa587',
    storageBucket: 'thriftly-fa587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDrJ5olJeWkGT3f2XfLXLn1dcgz2SK38',
    appId: '1:1005309051138:ios:26597d8af3a9e481aa021b',
    messagingSenderId: '1005309051138',
    projectId: 'thriftly-fa587',
    storageBucket: 'thriftly-fa587.appspot.com',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDrJ5olJeWkGT3f2XfLXLn1dcgz2SK38',
    appId: '1:1005309051138:ios:26597d8af3a9e481aa021b',
    messagingSenderId: '1005309051138',
    projectId: 'thriftly-fa587',
    storageBucket: 'thriftly-fa587.appspot.com',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUcFlTab9jaGA_KOYm7tGABIF7K6nqTs',
    appId: '1:1005309051138:web:b6408b9f4775e2b7aa021b',
    messagingSenderId: '1005309051138',
    projectId: 'thriftly-fa587',
    authDomain: 'thriftly-fa587.firebaseapp.com',
    storageBucket: 'thriftly-fa587.appspot.com',
    measurementId: 'G-49R1VLQZ4J',
  );
}
